services:
  witcher-dice-poker:
    image: ghcr.io/depermitto/witcher-dice-poker:latest
    container_name: witcher-dice-poker
    # logging:
    #   driver: journald
    ports:
      - "2007:2007"
    environment:
      APP_ENV: production
    healthcheck:
      test: [ "CMD", "/bin/busybox", "wget", "--quiet", "--spider", "http://localhost:2007/ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: on-failure
networks: {}
