services:
  witcher-dice-poker:
    build: ..
    image: witcher-dice-poker:1.0.0rc
    container_name: witcher-dice-poker
    ports:
      - "2007:2007"
    environment:
      WDP_SHOW_SWAGGER: 1
    healthcheck:
      test: [ "CMD", "/bin/busybox", "wget", "--quiet", "--spider", "http://localhost:2007/ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: on-failure
networks: {}
